.test_template: &test_definition
  stage: test
  script:
    - npm install --no-progress --no-colors
    - npm run test:lint
    - npm test

cache:
  paths:
    - node_modules

variables:
  NPM_CONFIG_LOGLEVEL: warn

stages:
  - test

#### Test jobs ####
test:node-6.1:
  image: node:6.1
  <<: *test_definition

test:node-5.11:
  image: node:5.11
  <<: *test_definition
